"""add order execution attempts

Revision ID: 0d0f249d9ec2
Revises: 302728569324
Create Date: 2026-06-24 22:47:39.347359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d0f249d9ec2"
down_revision: Union[str, Sequence[str], None] = "302728569324"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_execution_attempts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("recommendation_id", sa.BigInteger(), nullable=False),
        sa.Column("approval_request_id", sa.BigInteger(), nullable=False),
        sa.Column("order_log_id", sa.BigInteger(), nullable=True),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("trading_mode", sa.String(length=30), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["approval_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_log_id"],
            ["order_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["trade_recommendations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "recommendation_id",
            "trading_mode",
            "attempt_number",
            name="uq_order_execution_attempts_recommendation_mode_number",
        ),
    )
    op.create_index(
        op.f("ix_order_execution_attempts_approval_request_id"),
        "order_execution_attempts",
        ["approval_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_execution_attempts_order_log_id"),
        "order_execution_attempts",
        ["order_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_execution_attempts_recommendation_id"),
        "order_execution_attempts",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        "ix_order_execution_attempts_status_next_retry_at",
        "order_execution_attempts",
        ["status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_execution_attempts_user_id"),
        "order_execution_attempts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_execution_attempts_user_id"),
        table_name="order_execution_attempts",
    )
    op.drop_index(
        "ix_order_execution_attempts_status_next_retry_at",
        table_name="order_execution_attempts",
    )
    op.drop_index(
        op.f("ix_order_execution_attempts_recommendation_id"),
        table_name="order_execution_attempts",
    )
    op.drop_index(
        op.f("ix_order_execution_attempts_order_log_id"),
        table_name="order_execution_attempts",
    )
    op.drop_index(
        op.f("ix_order_execution_attempts_approval_request_id"),
        table_name="order_execution_attempts",
    )
    op.drop_table("order_execution_attempts")
    # ### end Alembic commands ###
