"""create market candles table

Revision ID: 2766db72643b
Revises: a30d611dc7e5
Create Date: 2026-06-20 22:07:52.212820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2766db72643b'
down_revision: Union[str, Sequence[str], None] = 'a30d611dc7e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('candle_type', sa.String(length=30), nullable=False),
    sa.Column('candle_unit', sa.Integer(), nullable=False),
    sa.Column('candle_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opening_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('trade_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('candle_acc_trade_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('candle_acc_trade_volume', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'market', 'candle_type', 'candle_unit', 'candle_at', name='uq_market_candles_exchange_market_type_unit_at')
    )
    op.create_index('ix_market_candles_exchange_market', 'market_candles', ['exchange', 'market'], unique=False)
    op.create_index('ix_market_candles_market_candle_at', 'market_candles', ['market', 'candle_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_candles_market_candle_at', table_name='market_candles')
    op.drop_index('ix_market_candles_exchange_market', table_name='market_candles')
    op.drop_table('market_candles')
    # ### end Alembic commands ###
