"""create initial tables

Revision ID: a30d611dc7e5
Revises: 36698f82fdd9
Create Date: 2026-06-20 16:55:27.476309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a30d611dc7e5'
down_revision: Union[str, Sequence[str], None] = '36698f82fdd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('trading_mode', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_user_id'), 'analysis_runs', ['user_id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('locked', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('avg_buy_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_analysis_run_id'), 'account_snapshots', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_currency'), 'account_snapshots', ['currency'], unique=False)
    op.create_index(op.f('ix_account_snapshots_user_id'), 'account_snapshots', ['user_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('change_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_analysis_run_id'), 'market_snapshots', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_market'), 'market_snapshots', ['market'], unique=False)
    op.create_index(op.f('ix_market_snapshots_user_id'), 'market_snapshots', ['user_id'], unique=False)
    op.create_table('trade_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('analysis_run_id', sa.BigInteger(), nullable=False),
    sa.Column('market_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommended_amount_krw', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('recommended_quantity', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['market_snapshot_id'], ['market_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_recommendations_analysis_run_id'), 'trade_recommendations', ['analysis_run_id'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_market'), 'trade_recommendations', ['market'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_market_snapshot_id'), 'trade_recommendations', ['market_snapshot_id'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_user_id'), 'trade_recommendations', ['user_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('callback_token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['trade_recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_token')
    )
    op.create_index(op.f('ix_approval_requests_recommendation_id'), 'approval_requests', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_user_id'), 'approval_requests', ['user_id'], unique=False)
    op.create_table('order_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.BigInteger(), nullable=False),
    sa.Column('approval_request_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('trading_mode', sa.String(length=30), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('market', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('amount_krw', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['trade_recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_logs_approval_request_id'), 'order_logs', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_order_logs_exchange_order_id'), 'order_logs', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_order_logs_market'), 'order_logs', ['market'], unique=False)
    op.create_index(op.f('ix_order_logs_recommendation_id'), 'order_logs', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_order_logs_status'), 'order_logs', ['status'], unique=False)
    op.create_index(op.f('ix_order_logs_user_id'), 'order_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_logs_user_id'), table_name='order_logs')
    op.drop_index(op.f('ix_order_logs_status'), table_name='order_logs')
    op.drop_index(op.f('ix_order_logs_recommendation_id'), table_name='order_logs')
    op.drop_index(op.f('ix_order_logs_market'), table_name='order_logs')
    op.drop_index(op.f('ix_order_logs_exchange_order_id'), table_name='order_logs')
    op.drop_index(op.f('ix_order_logs_approval_request_id'), table_name='order_logs')
    op.drop_table('order_logs')
    op.drop_index(op.f('ix_approval_requests_user_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_recommendation_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_trade_recommendations_user_id'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_market_snapshot_id'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_market'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_analysis_run_id'), table_name='trade_recommendations')
    op.drop_table('trade_recommendations')
    op.drop_index(op.f('ix_market_snapshots_user_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_market'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_analysis_run_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_account_snapshots_user_id'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_currency'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_analysis_run_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_analysis_runs_user_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('users')
    # ### end Alembic commands ###
