"""add order retry notifications

Revision ID: b880dce00b53
Revises: 0d0f249d9ec2
Create Date: 2026-06-25 22:56:19.898178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b880dce00b53"
down_revision: Union[str, Sequence[str], None] = "0d0f249d9ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_retry_notifications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("attempt_id", sa.BigInteger(), nullable=False),
        sa.Column("recommendation_id", sa.BigInteger(), nullable=False),
        sa.Column("approval_request_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("retry_status", sa.String(length=30), nullable=False),
        sa.Column(
            "delivery_status",
            sa.String(length=20),
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
        sa.Column(
            "retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approval_request_id"],
            ["approval_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["order_execution_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["trade_recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "attempt_id", name="uq_order_retry_notifications_attempt_id"
        ),
    )
    op.create_index(
        op.f("ix_order_retry_notifications_approval_request_id"),
        "order_retry_notifications",
        ["approval_request_id"],
        unique=False,
    )
    op.create_index(
        "ix_order_retry_notifications_delivery_next_retry",
        "order_retry_notifications",
        ["delivery_status", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_retry_notifications_recommendation_id"),
        "order_retry_notifications",
        ["recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_retry_notifications_recommendation_id"),
        table_name="order_retry_notifications",
    )
    op.drop_index(
        "ix_order_retry_notifications_delivery_next_retry",
        table_name="order_retry_notifications",
    )
    op.drop_index(
        op.f("ix_order_retry_notifications_approval_request_id"),
        table_name="order_retry_notifications",
    )
    op.drop_table("order_retry_notifications")
    # ### end Alembic commands ###
